import { OnboardingSubmission } from "@/types/onboarding";

// Property Manager onboarding submissions use the exact same shape as Landlord
// onboarding submissions (OnboardingSubmission) — the review experience is
// identical throughout; only the entityType field (and the label it drives)
// distinguishes a Property Manager submission from a Landlord one.
export const MOCK_PROPERTY_MANAGER_ONBOARDING_SUBMISSIONS: OnboardingSubmission[] = [
  {
    id: "pm-ob-001",
    entityType: "property_manager",
    landlordName: "Tunde Oginni",
    landlordPhone: "+234 803 222 1144",
    submittedAt: "2026-07-18T10:30:00.000Z",
    status: "pending",
    landlordInfo: {
      landlordType: "individual",
      firstName: "Tunde",
      lastName: "Oginni",
      dateOfBirth: "1983-09-12",
      email: "tunde.oginni@email.com",
      phone: "+234 803 222 1144",
      residentialAddress: "21 Alexander Avenue, Ikoyi, Lagos",
      meansOfIdentification: { name: "National ID Card", url: "/mock-documents/means-of-id.pdf" },
      photoOfIdentification: { name: "Passport Photograph", url: "/mock-documents/photo-id.pdf" },
    },
    services: ["Rent Collection", "Tenant Screening", "Maintenance Coordination", "Keys Handover"],
    properties: [
      {
        id: "pm-ob-001-p1",
        name: "Parkview Estate — Block C, Flat 3",
        description: "3 bedroom flat within a serviced estate.",
        address: "Parkview Estate, Ikoyi, Lagos",
        occupancyStatus: "occupied",
        rent: 2800000,
        serviceCharge: 350000,
        tenant: {
          name: "Ifeoma Chukwu",
          phone: "+234 802 441 7723",
          email: "ifeoma.chukwu@email.com",
        },
        tenancy: {
          tenancyType: "Annual",
          startDate: "2026-02-01",
          endDate: "2027-01-31",
        },
        documents: [
          { name: "Tenant KYC Form", url: "/mock-documents/kyc-form.pdf" },
          { name: "Tenancy Agreement", url: "/mock-documents/tenancy-agreement.pdf" },
        ],
        ownershipDocument: { name: "Certificate of Occupancy", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-001-p2",
        name: "Parkview Estate — Block C, Flat 4",
        description: "3 bedroom flat, mirror layout of Flat 3.",
        address: "Parkview Estate, Ikoyi, Lagos",
        occupancyStatus: "vacant",
        documents: [],
        ownershipDocument: { name: "Certificate of Occupancy", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-001-p3",
        name: "Parkview Estate — Block D, Flat 1",
        description: "2 bedroom flat on the ground floor.",
        address: "Parkview Estate, Ikoyi, Lagos",
        occupancyStatus: "occupied",
        rent: 2100000,
        serviceCharge: 280000,
        tenant: {
          name: "Bola Adisa",
          phone: "+234 807 220 5541",
          email: "bola.adisa@email.com",
        },
        tenancy: {
          tenancyType: "Annual",
          startDate: "2026-04-01",
          endDate: "2027-03-31",
        },
        documents: [
          { name: "Tenant KYC Form", url: "/mock-documents/kyc-form.pdf" },
          { name: "Tenancy Agreement", url: "/mock-documents/tenancy-agreement.pdf" },
        ],
        ownershipDocument: { name: "Certificate of Occupancy", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-001-p4",
        name: "Parkview Estate — Block D, Flat 2",
        description: "2 bedroom flat, mirror layout of Flat 1.",
        address: "Parkview Estate, Ikoyi, Lagos",
        occupancyStatus: "vacant",
        documents: [],
        ownershipDocument: { name: "Certificate of Occupancy", url: "/mock-documents/proof-of-ownership.pdf" },
      },
    ],
  },
  {
    id: "pm-ob-002",
    entityType: "property_manager",
    landlordName: "Amaka Properties",
    landlordPhone: "+234 806 441 2288",
    submittedAt: "2026-07-19T15:05:00.000Z",
    status: "pending",
    landlordInfo: {
      landlordType: "corporate",
      companyName: "Amaka Properties Ltd",
      officeAddress: "8 Idejo Street, Victoria Island, Lagos",
      contactFirstName: "Amaka",
      contactLastName: "Eze",
      contactPhone: "+234 806 441 2288",
      cacDocument: { name: "CAC Certificate", url: "/mock-documents/cac-certificate.pdf" },
    },
    services: ["Property Marketing", "Tenant Screening", "Tenant Offer Letter & Tenancy Agreement", "Rent Collection", "Tenant Support", "Maintenance Coordination"],
    properties: [
      {
        id: "pm-ob-002-p1",
        name: "Marina Heights — Unit 5A",
        description: "1 bedroom apartment with waterfront view.",
        address: "Marina Heights, Victoria Island, Lagos",
        occupancyStatus: "occupied",
        rent: 1800000,
        serviceCharge: 220000,
        tenant: {
          name: "Kelechi Nnamdi",
          phone: "+234 813 662 9091",
          email: "kelechi.nnamdi@email.com",
        },
        tenancy: {
          tenancyType: "Annual",
          startDate: "2026-05-01",
          endDate: "2027-04-30",
        },
        documents: [
          { name: "Tenant KYC Form", url: "/mock-documents/kyc-form.pdf" },
          { name: "Tenancy Agreement", url: "/mock-documents/tenancy-agreement.pdf" },
        ],
        ownershipDocument: { name: "Deed of Assignment", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-002-p2",
        name: "Marina Heights — Unit 5B",
        description: "1 bedroom apartment, mirror layout of 5A.",
        address: "Marina Heights, Victoria Island, Lagos",
        occupancyStatus: "occupied",
        rent: 1800000,
        serviceCharge: 220000,
        tenant: {
          name: "Ngozi Uba",
          phone: "+234 809 774 1120",
          email: "ngozi.uba@email.com",
        },
        tenancy: {
          tenancyType: "Annual",
          startDate: "2026-03-01",
          endDate: "2027-02-28",
        },
        documents: [
          { name: "Tenant KYC Form", url: "/mock-documents/kyc-form.pdf" },
          { name: "Tenancy Agreement", url: "/mock-documents/tenancy-agreement.pdf" },
        ],
        ownershipDocument: { name: "Deed of Assignment", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-002-p3",
        name: "Marina Heights — Unit 6A",
        description: "2 bedroom apartment on the 6th floor.",
        address: "Marina Heights, Victoria Island, Lagos",
        occupancyStatus: "vacant",
        documents: [],
        ownershipDocument: { name: "Deed of Assignment", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-002-p4",
        name: "Marina Heights — Unit 6B",
        description: "2 bedroom apartment, mirror layout of 6A.",
        address: "Marina Heights, Victoria Island, Lagos",
        occupancyStatus: "vacant",
        documents: [],
        ownershipDocument: { name: "Deed of Assignment", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-002-p5",
        name: "Marina Heights — Unit 7A",
        description: "2 bedroom apartment on the 7th floor.",
        address: "Marina Heights, Victoria Island, Lagos",
        occupancyStatus: "occupied",
        rent: 2000000,
        serviceCharge: 240000,
        tenant: {
          name: "Femi Balogun",
          phone: "+234 815 990 3312",
          email: "femi.balogun@email.com",
        },
        tenancy: {
          tenancyType: "Annual",
          startDate: "2026-06-01",
          endDate: "2027-05-31",
        },
        documents: [
          { name: "Tenant KYC Form", url: "/mock-documents/kyc-form.pdf" },
          { name: "Tenancy Agreement", url: "/mock-documents/tenancy-agreement.pdf" },
        ],
        ownershipDocument: { name: "Deed of Assignment", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-002-p6",
        name: "Marina Heights — Unit 7B",
        description: "2 bedroom apartment, mirror layout of 7A.",
        address: "Marina Heights, Victoria Island, Lagos",
        occupancyStatus: "vacant",
        documents: [],
        ownershipDocument: { name: "Deed of Assignment", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-002-p7",
        name: "Marina Heights — Penthouse",
        description: "3 bedroom penthouse with private terrace.",
        address: "Marina Heights, Victoria Island, Lagos",
        occupancyStatus: "vacant",
        documents: [],
        ownershipDocument: { name: "Deed of Assignment", url: "/mock-documents/proof-of-ownership.pdf" },
      },
    ],
  },
  {
    id: "pm-ob-003",
    entityType: "property_manager",
    landlordName: "David Okoro",
    landlordPhone: "+234 812 775 3301",
    submittedAt: "2026-07-20T09:15:00.000Z",
    status: "pending",
    landlordInfo: {
      landlordType: "individual",
      firstName: "David",
      lastName: "Okoro",
      dateOfBirth: "1988-02-27",
      email: "david.okoro@email.com",
      phone: "+234 812 775 3301",
      residentialAddress: "6 Muri Okunola Street, Victoria Island, Lagos",
      meansOfIdentification: { name: "International Passport", url: "/mock-documents/means-of-id.pdf" },
      photoOfIdentification: { name: "Passport Photograph", url: "/mock-documents/photo-id.pdf" },
    },
    services: ["Rent Collection", "Tenant Support"],
    properties: [
      {
        id: "pm-ob-003-p1",
        name: "Chevron Drive Apartments — Unit 3",
        description: "2 bedroom apartment close to the Lekki-Chevron axis.",
        address: "Chevron Drive, Lekki, Lagos",
        occupancyStatus: "occupied",
        rent: 1600000,
        serviceCharge: 190000,
        tenant: {
          name: "Yemisi Alade",
          phone: "+234 803 552 6640",
          email: "yemisi.alade@email.com",
        },
        tenancy: {
          tenancyType: "Annual",
          startDate: "2026-01-15",
          endDate: "2027-01-14",
        },
        documents: [
          { name: "Tenant KYC Form", url: "/mock-documents/kyc-form.pdf" },
          { name: "Tenancy Agreement", url: "/mock-documents/tenancy-agreement.pdf" },
        ],
        ownershipDocument: { name: "Certificate of Occupancy", url: "/mock-documents/proof-of-ownership.pdf" },
      },
      {
        id: "pm-ob-003-p2",
        name: "Chevron Drive Apartments — Unit 4",
        description: "2 bedroom apartment, mirror layout of Unit 3.",
        address: "Chevron Drive, Lekki, Lagos",
        occupancyStatus: "vacant",
        documents: [],
        ownershipDocument: { name: "Certificate of Occupancy", url: "/mock-documents/proof-of-ownership.pdf" },
      },
    ],
  },
];
